### PR TITLE
Upgrade ckb dependencies to `0.111.0`, use `cargo-nextest` to run unit tests

### PR DESCRIPTION
**Pull request by eval-exec**
This PR do these changes;
1. `chrry-picked` https://github.com/nervosnetwork/ckb-light-client/commit/ac8b3c9f21b0076ef43b58197b67adb394205100 
2. use `cargo nextest run` to run unit tests

### CODE REVIEW

**Comment by eval-exec** [comment]
@quake Please help me trigger the CI action. I want to know if my changes can make the CI on the Windows platform successfully complete.

**Comment by eval-exec** [comment]
@quake Please re-trigger the CI action.

**Review by quake — APPROVED** [review]

**Comment by homura** [comment]
Hi, is there a plan to create a release for this PR?

**Comment by quake** [comment]
we are testing this PR, but we don't have a confirmed release date yet.

**Pull request merged**
